---
title: "Client Report - [US name history index]"
subtitle: "Course DS 250"
author: "[Cannon Roach]"
format:
  html:
    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap
    code-copy: hover
    code-tools:
        source: false
        toggle: true
        caption: See code
execute: 
  warning: false
    
---

```{python}
# | label: libraries
# | include: false
import pandas as pd
import numpy as np
import plotly.express as px
```


## Elevator pitch

_This project is a result of the query method in pandas. With the prompts provided, I have made graphs to visualize the data. Answering the questions, I have learned that names through time change in use based on fads/trends. The use of a name can go down and up in time._

```{python}
#| label: project data
#| code-summary: Read and format project data
# Include and execute your code here
df = pd.read_csv("https://github.com/byuidatascience/data4names/raw/master/data-raw/names_year/names_year.csv")
```


## QUESTION|TASK 1

__How does your name at your birth year compare to its use historically?__

_My Birthyear was about the halfway point of the peakvuse of the name Cannon._

```{python}
#| label: Q1
#| code-summary: Read and format data
# Include and execute your code here
cannon = px.line(df.query('name == "Cannon"'), x="year", y="Total", title="Cannons naming history")
cannon.add_annotation(x=2005, y=208, text="My Birthyear")
cannon.show()
```


```{python}
#| label: Q1 table
#| code-summary: table example
#| tbl-cap: "Not much of a table"
#| tbl-cap-location: top
# Include and execute your code here
mydat = df.head(1000)\
    .groupby('year')\
    .sum()\
    .reset_index()\
    .tail(10)\
    .filter(["year", "AK","AR"])

display(mydat)

```


## QUESTION|TASK 2

__If you talked to someone named Brittany on the phone, what is your guess of his or her age? What ages would you not guess?__

_I would guess the age of Brittany to be 33 because of the amount of people named Brittany in 1990. I would not guess 55-56 because of the 5 people named Brittany then._

```{python}
#| label: Q2
#| code-summary: Read and format data
# Include and execute your code here
brit = px.line(df.query('name == "Brittany"'), x="year", y="Total")
brit.add_annotation(x=1990, y=32562, text="33 to 34")
brit.add_annotation(x=1968, y=5, text="55 to 56")
brit.show()

```


```{python}
#| label: Q2 chart
#| code-summary: plot example
#| fig-cap: "My useless chart"
#| fig-align: center
# Include and execute your code here
chart = px.bar(df.head(200),
    x="name", 
    y="AK"
)
chart.show()
```


```{python}
#| label: Q2 table
#| code-summary: table example
#| tbl-cap: "Not much of a table"
#| tbl-cap-location: top
# Include and execute your code here
mydat = df.head(1000)\
    .groupby('year')\
    .sum()\
    .reset_index()\
    .tail(10)\
    .filter(["year", "AK","AR"])

display(mydat)

```


## QUESTION|TASK 3

__Mary, Martha, Peter, and Paul are all Christian names. From 1920 - 2000, compare the name usage of each of the four names. What trends do you notice?__

_from 1920-1968 Mary was the most common name of the four. But in 1968, Paul passed slightly, than they were close ever since.The use of Martha has been lowest since 1954_

```{python}
#| label: Q3
#| code-summary: Read and format data
# Include and execute your code here
christian = px.line(df.query('(name == "Peter" or name == "Paul" or name == "Martha" or name == "Mary") and 1919 < year < 2001'), x="year", y="Total", color="name")
christian.show()
```


```{python}
#| label: Q3 table
#| code-summary: table example
#| tbl-cap: "Not much of a table"
#| tbl-cap-location: top
# Include and execute your code here
mydat = df.head(1000)\
    .groupby('year')\
    .sum()\
    .reset_index()\
    .tail(10)\
    .filter(["year", "AK","AR"])

display(mydat)

```
## QUESTION|TASK 4

__Think of a unique name from a famous movie. Plot the usage of that name and see how changes line up with the movie release. Does it look like the movie had an effect on usage?__

_The graph below shoes the history of all people named Anakin. The first starwars movie came out in 1977. Before 1998 there was never someone named Anakin in the database. The star wars movies lead to people being named Anakin_

```{python}
#| label: Q4
#| code-summary: Read and format data
# Include and execute your code here
starwars = px.line(df.query('name == "Anakin"'), x="year", y="Total")
starwars.show()

```